/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankManagementSystem.View;

import All.IDgenerator;
import BankManagementSystem.Controller.CustomerController;
import BankManagementSystem.Model.CustomerModel;
import static BankManagementSystem.View.MainForm.mainPanel;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author NEOx
 */
public class CustomerRegistration extends javax.swing.JInternalFrame {

    /**
     * Creates new form CustomerRegistration
     */
    public CustomerRegistration() {
        initComponents();
        autoTime();
        autoDate();
        fNametxt.requestFocus();
        getID();
        NICtxt.setText(null);
       
    }
    
    private void autoTime(){
    new Thread (new Runnable() {
        public void run (){
            while(true){
                Date time = new Date();
                String curDate=new SimpleDateFormat("hh:mm:ss aa").format(time);
                timelbl.setText(curDate);
                try{
                    Thread.sleep(1000);
                }catch(InterruptedException ex){
                    
                }
            }
        }
    }).start();

}

     private void autoDate(){
        Date date=new Date();
        SimpleDateFormat curDate=new SimpleDateFormat("yyyy-MM-dd");
        String newDate=curDate.format(date);
        datelbl.setText(newDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        occtxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addresstxt = new javax.swing.JTextArea();
        datelbl = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        NICtxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        timelbl = new javax.swing.JLabel();
        mbotxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        DOBtxt = new com.toedter.calendar.JDateChooser();
        fNametxt = new javax.swing.JTextField();
        CIDtxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lNametxt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        agetxt = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/backButton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 920, 150, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/nextButton.png"))); // NOI18N
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 920, 150, 50));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Occupation");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, 210, 50));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText(":");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 460, 20, 50));

        occtxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        occtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occtxtActionPerformed(evt);
            }
        });
        occtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                occtxtKeyReleased(evt);
            }
        });
        jPanel1.add(occtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 470, 430, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(":");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 20, 50));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("NIC");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 210, 50));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Date of Birth");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, 210, 50));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText(":");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 20, 50));

        addresstxt.setColumns(20);
        addresstxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addresstxt.setRows(5);
        jScrollPane2.setViewportView(addresstxt);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 260, 430, -1));

        datelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        datelbl.setForeground(new java.awt.Color(255, 255, 255));
        datelbl.setText("16");
        jPanel1.add(datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, 320, -1));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-vertical-line.png"))); // NOI18N
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 20, 30, 90));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Years");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, 100, 50));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(":");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 20, 50));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText(":");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 260, 20, 50));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(":");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 20, 50));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText(":");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, 20, 50));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText(":");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 530, 20, 50));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Register New Customer");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 450, 70));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(":");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 20, 50));

        NICtxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NICtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NICtxtActionPerformed(evt);
            }
        });
        NICtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NICtxtKeyReleased(evt);
            }
        });
        jPanel1.add(NICtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 430, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Address");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 250, 210, 70));

        timelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        timelbl.setForeground(new java.awt.Color(255, 255, 255));
        timelbl.setText("08:16:00");
        jPanel1.add(timelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 20, 360, 90));

        mbotxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mbotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mbotxtKeyReleased(evt);
            }
        });
        jPanel1.add(mbotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 540, 430, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Mobile no.");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 530, 210, 50));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Gender");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 720, 210, 50));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText(":");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 720, 20, 50));

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.setOpaque(false);
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 730, 140, 30));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        male.setOpaque(false);
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 730, 130, 30));
        jPanel1.add(DOBtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 420, 30));

        fNametxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNametxtActionPerformed(evt);
            }
        });
        fNametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fNametxtKeyReleased(evt);
            }
        });
        jPanel1.add(fNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 430, -1));

        CIDtxt.setEditable(false);
        CIDtxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIDtxtActionPerformed(evt);
            }
        });
        CIDtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CIDtxtKeyReleased(evt);
            }
        });
        jPanel1.add(CIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 430, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("First Name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 210, 70));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Last Name");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 210, 70));

        lNametxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNametxtActionPerformed(evt);
            }
        });
        lNametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lNametxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lNametxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lNametxtKeyTyped(evt);
            }
        });
        jPanel1.add(lNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 430, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/existingC1.PNG"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 160, 420, 70));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Age");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 640, 130, 50));

        agetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(agetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 650, 130, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 210, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Details");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 880, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-horizontal-line.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1910, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 2090, 1060));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1060));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1060));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1920, 1060));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1060));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1060));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/istock000003037994medium.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 1100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Homepage h1 = new Homepage();
        mainPanel.removeAll();
        mainPanel.add(h1);
        h1.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String CID = CIDtxt.getText();
       
            String fName = fNametxt.getText();
               String lName = lNametxt.getText();
               SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
               String DOB=sdf.format(DOBtxt.getDate());
               String age =Integer.toString((int) agetxt.getValue());
               String gender=null;
               if(male.isSelected()){
                   gender="male";
               }else{
                   gender="female";
               }
               String address = addresstxt.getText();
               String NIC = NICtxt.getText();
               String occ = occtxt.getText();
               String mbo = mbotxt.getText();
       
               CustomerModel cst=new CustomerModel(CID,fName,lName,DOB,age,gender,address,occ,NIC,mbo);
        
               try {
                   boolean res=CustomerController.addCustomer(cst);
                   if(res){
                       JOptionPane.showMessageDialog(this,"Customer Added Successfully..!!");
                   }else{
                JOptionPane.showMessageDialog(this,"Customer Added Failed..!!");
                   }
               } catch (ClassNotFoundException ex) {
                   Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
               } catch (SQLException ex) {
                   Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
               }        
               
        
               OpenAnAccount a1 = new OpenAnAccount();
               this.hide();
               //mainPanel.removeAll();
               mainPanel.add(a1);
               a1.setVisible(true);
               a1.txtId.setText(CID);
               a1.txtName.setText(fName+" "+lName);
               a1.txtDate.setText(datelbl.getText());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void DOBtxtComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_DOBtxtComponentAdded
      
    }//GEN-LAST:event_DOBtxtComponentAdded

    private void CIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIDtxtActionPerformed
        fNametxt.requestFocus();
    }//GEN-LAST:event_CIDtxtActionPerformed

    private void fNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNametxtActionPerformed
        lNametxt.requestFocus();
    }//GEN-LAST:event_fNametxtActionPerformed

    private void lNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNametxtActionPerformed
        NICtxt.requestFocus();
    }//GEN-LAST:event_lNametxtActionPerformed

    private void DOBtxtAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_DOBtxtAncestorAdded
       
    }//GEN-LAST:event_DOBtxtAncestorAdded

    private void NICtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NICtxtActionPerformed
        if(NICtxt.getText() != null){
            String NIC=NICtxt.getText();
            String syy=NIC.substring(0,2);
            String smm=NIC.substring(2,5);
            int yy=Integer.parseInt(19+syy);
            int mm=Integer.parseInt(smm);
            
            if(mm>=500){
		female.setSelected(true);
                mm-=500;
            }else{
                male.setSelected(true);
            }	
            
            if(yy % 4 != 0){
                mm=mm-1;
            }
            
            Calendar c1=Calendar.getInstance();
            c1.set(Calendar.YEAR, yy);
            c1.set(Calendar.DAY_OF_YEAR, mm);
            Date d1=c1.getTime();
            DOBtxt.setDate(d1);
            
            Date date=new Date();
            SimpleDateFormat curDate=new SimpleDateFormat("yyyy");
            String newDate=curDate.format(date);
            int year=Integer.parseInt(newDate);
            
            int age = year-yy;
            agetxt.setValue(age);
            addresstxt.requestFocus();
        }else{
            NICtxt.setText("None");
        }
    }//GEN-LAST:event_NICtxtActionPerformed

    private void occtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occtxtActionPerformed
        mbotxt.requestFocus();
    }//GEN-LAST:event_occtxtActionPerformed

    private void mbotxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mbotxtKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.phoneNumber(mbotxt, evt);
        }
        
        if(fNametxt.getText().length()>0){
            jButton2.setEnabled(true);
        }
    }//GEN-LAST:event_mbotxtKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ExistingCustomer e1 = new ExistingCustomer();
        mainPanel.removeAll();
        mainPanel.add(e1);
        e1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited

    }//GEN-LAST:event_jButton3MouseExited

    
    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered

    }//GEN-LAST:event_jButton3MouseEntered

    private void CIDtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CIDtxtKeyReleased
        
    }//GEN-LAST:event_CIDtxtKeyReleased

    private void NICtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NICtxtKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.validateNIC(NICtxt);
        }
    }//GEN-LAST:event_NICtxtKeyReleased

    private void fNametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNametxtKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.name(fNametxt);
        }
    }//GEN-LAST:event_fNametxtKeyReleased

    private void lNametxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNametxtKeyPressed
       
    }//GEN-LAST:event_lNametxtKeyPressed

    private void lNametxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNametxtKeyTyped
        
    }//GEN-LAST:event_lNametxtKeyTyped

    private void lNametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNametxtKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.name(lNametxt);
        }
    }//GEN-LAST:event_lNametxtKeyReleased

    private void occtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_occtxtKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.name(occtxt);
        }
    }//GEN-LAST:event_occtxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CIDtxt;
    private com.toedter.calendar.JDateChooser DOBtxt;
    private javax.swing.JTextField NICtxt;
    private javax.swing.JTextArea addresstxt;
    private javax.swing.JSpinner agetxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel datelbl;
    private javax.swing.JTextField fNametxt;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lNametxt;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mbotxt;
    private javax.swing.JTextField occtxt;
    private javax.swing.JLabel timelbl;
    // End of variables declaration//GEN-END:variables
    public  void getID(){
       String newID;
        try {
            newID=IDgenerator.autoID("Customer", "CID", "C");
            CIDtxt.setText(newID);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }

}
