/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankManagementSystem.View;

import All.IDgenerator;
import BankManagementSystem.Controller.AccountController;
import BankManagementSystem.Controller.AccountTypeController;
import BankManagementSystem.Controller.CustomerController;
import BankManagementSystem.Controller.TransactionController;
import BankManagementSystem.Model.AccountModel;
import BankManagementSystem.Model.AccountTypeModel;
import BankManagementSystem.Model.CustomerModel;
import BankManagementSystem.Model.TransactionModel;
import static BankManagementSystem.View.MainForm.mainPanel;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.util.calendar.CalendarUtils;

/**
 *
 * @author NEOx
 */
public class Deposit extends javax.swing.JInternalFrame {

    /**
     * Creates new form Deposit
     */
    public Deposit() {
        initComponents();
        autoTime();
        autoDate();
        getID();
        txtactID.requestFocus();
    }
    private void autoTime(){
    new Thread (new Runnable() {
        public void run (){
            while(true){
                Date time = new Date();
                String curDate=new SimpleDateFormat("hh:mm:ss aa").format(time);
                timelbl.setText(curDate);
                try{
                    Thread.sleep(1000);
                }catch(InterruptedException ex){
                    
                }
            }
        }
    }).start();

}
    private void autoDate(){
        Date date=new Date();
        SimpleDateFormat curDate=new SimpleDateFormat("yyyy-MM-dd");
        String newDate=curDate.format(date);
        datelbl.setText(newDate);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtactHolder = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtactholderName = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtAccountType = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        timelbl = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtTID = new javax.swing.JTextField();
        txtAmountInWords = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        txtactID = new javax.swing.JTextField();
        txt5000 = new javax.swing.JSpinner();
        txt1000 = new javax.swing.JSpinner();
        txt500 = new javax.swing.JSpinner();
        txt100 = new javax.swing.JSpinner();
        txt50 = new javax.swing.JSpinner();
        txt20 = new javax.swing.JSpinner();
        txt10 = new javax.swing.JSpinner();
        txt5 = new javax.swing.JSpinner();
        txt2000 = new javax.swing.JSpinner();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        txtdepositorName2 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-horizontal-line.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1910, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/confirmButton.png"))); // NOI18N
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 920, 150, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/backButton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 920, 150, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Money Deposit");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 880, 80));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Account ID");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 210, 50));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText(":");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 20, 50));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText(":");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 20, 50));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText(":");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 20, 50));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText(":");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 20, 50));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText(":");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 830, 20, 50));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Account holder");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 250, 50));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("ID");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 50, 50));

        txtactHolder.setEditable(false);
        txtactHolder.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(txtactHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 430, -1));

        txtDate.setEditable(false);
        txtDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 170, 430, -1));

        txtactholderName.setEditable(false);
        txtactholderName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(txtactholderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 430, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Account holder");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 250, 50));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Name");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 250, 50));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Account Type");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 250, 50));

        txtAccountType.setEditable(false);
        txtAccountType.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(txtAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 430, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Amount in words");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 830, 260, 50));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Date");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 160, 130, 50));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText(":");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 160, 20, 50));

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Amount ,");
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 260, 150, 50));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText(":");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 320, 20, 50));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Rs.5000");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 320, 150, 50));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText(":");
        getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 370, 20, 50));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Rs.2000");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 370, 150, 50));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText(":");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 420, 20, 50));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Rs.1000");
        getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 420, 150, 50));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText(":");
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 670, 20, 50));

        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        getContentPane().add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 790, 430, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText(":");
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 470, 20, 50));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-vertical-line.png"))); // NOI18N
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 20, 30, 90));

        datelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        datelbl.setForeground(new java.awt.Color(255, 255, 255));
        datelbl.setText("16");
        getContentPane().add(datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, 320, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Rs.500");
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 470, 150, 50));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText(":");
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 520, 20, 50));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Rs.100");
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 520, 150, 50));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText(":");
        getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 570, 20, 50));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Rs.50");
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 570, 150, 50));

        timelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        timelbl.setForeground(new java.awt.Color(255, 255, 255));
        timelbl.setText("08:16:00");
        getContentPane().add(timelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 20, 360, 90));

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText(":");
        getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 620, 20, 50));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Rs.20");
        getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 620, 150, 50));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Transaction ID");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 270, 50));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText(":");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 20, 50));

        txtTID.setEditable(false);
        txtTID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtTID, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 430, -1));

        txtAmountInWords.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtAmountInWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountInWordsActionPerformed(evt);
            }
        });
        getContentPane().add(txtAmountInWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 840, 750, -1));

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Rupees");
        getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 830, 90, 50));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Rs.10");
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 670, 150, 50));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText(":");
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 720, 20, 50));

        lbl5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lbl5.setForeground(new java.awt.Color(255, 255, 255));
        lbl5.setText("Rs.5");
        getContentPane().add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 720, 150, 50));

        txtactID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtactID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtactIDActionPerformed(evt);
            }
        });
        txtactID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtactIDKeyReleased(evt);
            }
        });
        getContentPane().add(txtactID, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 430, -1));

        txt5000.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txt5000, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 330, 200, 30));

        txt1000.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txt1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 430, 200, 30));

        txt500.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txt500, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 480, 200, 30));

        txt100.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txt100, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 530, 200, 30));

        txt50.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txt50, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 580, 200, 30));

        txt20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txt20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 630, 200, 30));

        txt10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 680, 200, 30));

        txt5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 730, 200, 30));

        txt2000.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txt2000, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 380, 200, 30));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("__________________________________");
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 740, 670, 50));

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText(":");
        getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 780, 20, 50));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Current Balance");
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 270, 50));

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText(":");
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, 20, 50));

        txtBalance.setEditable(false);
        txtBalance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 430, -1));

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText(":");
        getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 700, 20, 50));

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Dipositor Name");
        getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 700, 250, 50));

        txtdepositorName2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtdepositorName2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdepositorName2KeyReleased(evt);
            }
        });
        getContentPane().add(txtdepositorName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 710, 430, -1));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Total");
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 780, 150, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1910, 1070));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/istock000003037994medium.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 1100));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1910, 1070));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String TID=txtTID.getText();
        String AID=txtactID.getText();
        String date=datelbl.getText();
        double crntBal=Double.parseDouble(txtBalance.getText());
        double trAmount=Double.parseDouble(txtAmount.getText());
        String transactorName=txtdepositorName2.getText();
        String transactionType="Deposit";
        double amount=Double.parseDouble(txtAmount.getText());
        
        AccountModel act1=null;
        try {
            act1=AccountController.searchAccount(AID);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String CID=act1.getCID();
        String accountType=act1.getAccountType();
        String guardian=act1.getGuardianName();
        double newAmount=crntBal+trAmount;
            
        TransactionModel tr=new TransactionModel(TID, AID, transactorName, date, transactionType, amount);
        AccountModel act2=new AccountModel(AID, CID,accountType ,guardian, newAmount);
        
        try {
            boolean res=TransactionController.addTransaction(tr);
            boolean res2=AccountController.updateAccount(act2);
            
            if(res){
                JOptionPane.showMessageDialog(this,"Transaction Successfull..");
                Homepage h1 = new Homepage();
                mainPanel.removeAll();
                mainPanel.add(h1);
                h1.setVisible(true);

            }else{
                JOptionPane.showMessageDialog(this,"Transaction Failed..");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       MoneyTransactionMenu t1 =new MoneyTransactionMenu();
        mainPanel.removeAll();
        mainPanel.add(t1);
        t1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtTIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTIDActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        int r5000=((int) txt5000.getValue()*5000);
        int r2000=((int) txt2000.getValue()*2000);
        int r1000=((int) txt1000.getValue()*1000);
        int r500=((int) txt500.getValue())*500;
        int r100=((int) txt100.getValue())*100;
        int r50=((int) txt50.getValue())*50;
        int r20=((int) txt20.getValue())*20;
        int r10=((int) txt10.getValue())*10;
        int r5=((int) txt5.getValue())*5;
        
        int total=r5000+r2000+r1000+r500+r100+r50+r20+r10+r5;
        txtAmount.setText(Integer.toString(total));

        int amount=Integer.parseInt(txtAmount.getText());
        txtAmountInWords.setText(convert(amount));
        txtAmountInWords.requestFocus();
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtactIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtactIDActionPerformed
        txtdepositorName2.requestFocus();
        txtAmount.setText(null);
        txtAmountInWords.setText(null);
        String actID=txtactID.getText();
        AccountModel actm;
        try {
            actm = AccountController.searchAccount(actID);
            if(actm!=null){
                String ACTID=actm.getAccountType();
                String actHolderID=actm.getCID();
                CustomerModel cstm=CustomerController.searchCustomer(actHolderID);
                String actHolderName1=cstm.getfName();
                String actHolderName2=cstm.getlName();
                
                AccountTypeModel accountType=AccountTypeController.searchAccountTypeID(ACTID);
                String accountTypeName=accountType.getName();
                
                txtactHolder.setText(actHolderID);
                txtAccountType.setText(accountTypeName);
                txtactholderName.setText(actHolderName1+" "+actHolderName2);
                txtBalance.setText(Double.toString(actm.getBalance()));
            }else{
                JOptionPane.showMessageDialog(this, "Account was not Found..!!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_txtactIDActionPerformed

    private void txtAmountInWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountInWordsActionPerformed
        jButton3.setEnabled(true);
    }//GEN-LAST:event_txtAmountInWordsActionPerformed

    private void txtactIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtactIDKeyReleased
        
    }//GEN-LAST:event_txtactIDKeyReleased

    private void txtdepositorName2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdepositorName2KeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.name(txtdepositorName2);
        }
    }//GEN-LAST:event_txtdepositorName2KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datelbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel timelbl;
    private javax.swing.JSpinner txt10;
    private javax.swing.JSpinner txt100;
    private javax.swing.JSpinner txt1000;
    private javax.swing.JSpinner txt20;
    private javax.swing.JSpinner txt2000;
    private javax.swing.JSpinner txt5;
    private javax.swing.JSpinner txt50;
    private javax.swing.JSpinner txt500;
    private javax.swing.JSpinner txt5000;
    public static javax.swing.JTextField txtAccountType;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtAmountInWords;
    public static javax.swing.JTextField txtBalance;
    public static javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtTID;
    public static javax.swing.JTextField txtactHolder;
    public static javax.swing.JTextField txtactID;
    public static javax.swing.JTextField txtactholderName;
    private javax.swing.JTextField txtdepositorName2;
    // End of variables declaration//GEN-END:variables
       String a=" ";
    
    private String oneToHundred(int amount){
        String a1=" ";
        while( amount!=0){
            if(amount==1){
                a1=a1+"One";
                amount=0;
            }else if( amount ==2 ){
                a1=a1+"Two";
                amount=0;
            }else if( amount ==3 ){
                a1=a1+"Three";
                amount=0;
            }else if( amount ==4 ){
                a1=a1+"Four";
                amount=0;
            }else if( amount ==5 ){
                a1=a1+"Five";
                amount=0;
            }else if( amount ==6 ){
                a1=a1+"Six";
                amount=0;
            }else if( amount ==7 ){
                a1=a1+"Seven";
                amount=0;
            }else if( amount ==8 ){
                a1=a1+"Eight";
                amount=0;
            }else if( amount ==9 ){
                a1=a1+"Nine";
                amount=0;
            }else if( amount ==10 ){
                a1=a1+"Ten";
                amount=0;
            }else if( amount ==11 ){
                a1=a1+"Eleven";
                amount=0;
            }else if( amount ==12){
                a1=a1+"Twelve";
                amount=0;
            }else if( amount ==13){
                a1=a1+"Thirteen";
                amount=0;
            }else if( amount ==14){
                a1=a1+"Fourteen";
                amount=0;
            }else if( amount ==15){
                a1=a1+"Fifteen";
                amount=0;
            }else if( amount ==16){
                a1=a1+"Sixteen";
                amount=0;
            }else if( amount ==17){
                a1=a1+"Seventeen";
                amount=0;
            }else if( amount ==18){
                a1=a1+"Eighteen";
                amount=0;
            }else if( amount ==19){
                a1=a1+"Nineteen";
                amount=0;
            }else if(amount>=20 && amount <30){
                a1=a1+"Twenty ";
                amount=amount-20;
            }else if(amount>=30 && amount <40){
                a1=a1+"Thirty ";
                amount=amount-30;
            }else if(amount>=40 && amount <50){
                a1=a1+"Fourty ";
                amount=amount-40;
            }else if(amount>=50 && amount <60){
                a1=a1+"Fifty ";
                amount=amount-50;
            }else if(amount>=60 && amount <70){
                a1=a1+"Sixty ";
                amount=amount-60;
            }else if(amount>=70 && amount <80){
                a1=a1+"Seventy ";
                amount=amount-70;
            }else if(amount>=80 && amount <90){
                a1=a1+"Eighty ";
                amount=amount-80;
            }else if(amount>=90 && amount <100){
                a1=a1+"Ninety ";
                amount=amount-90;
            }
        }
        
        return a1;
    }

    private String convert(int amount){
        String a1=" ";
        
        while(amount != 0){
            if(amount >=1 && amount <100){
                a1=a1+oneToHundred(amount);
                amount=0;
            }else if(amount >= 100 && amount < 1000){
                a1=a1+oneToHundred(amount/100);
                a1=a1+" Hundred ";
                amount = amount % 100;
            }else if(amount >= 1000 && amount < 10000){
                a1=a1+oneToHundred(amount/1000);
                a1=a1+" Thousand";
                amount = amount % 1000;
            }else if(amount >= 10000 && amount < 100000){
                a1=a1+oneToHundred(amount/1000);
                a1=a1+" Thousand";
                amount = amount % 1000;
            }else if(amount >= 100000 && amount <10000000){
                a1=a1+oneToHundred(amount/100000);
                a1=a1+" Lakh";
                amount = amount % 100000;
            }
        }
        
        return a1;
    }
    
    public  void getID(){
       String newID;
        try {
            newID=IDgenerator.autoID("transaction", "TID", "T");
            txtTID.setText(newID);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }

}
