/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankManagementSystem.View;

import BankManagementSystem.Controller.BlacklistcustomerController;
import BankManagementSystem.Controller.CustomerController;
import BankManagementSystem.Model.BlacklistCustomerModel;
import BankManagementSystem.Model.CustomerModel;
import static BankManagementSystem.View.MainForm.mainPanel;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.transform.Source;

/**
 *
 * @author NEOx
 */
public class ExistingCustomer extends javax.swing.JInternalFrame {

    /**
     * Creates new form ExistingCustomer
     */
    public ExistingCustomer() {
        initComponents();
        autoDate();
        autoTime();
    }

    private void autoTime(){
    new Thread (new Runnable() {
        public void run (){
            while(true){
                Date time = new Date();
                String curDate=new SimpleDateFormat("hh:mm:ss aa").format(time);
                timelbl.setText(curDate);
                try{
                    Thread.sleep(1000);
                }catch(InterruptedException ex){
                    
                }
            }
        }
    }).start();

}
     private void autoDate(){
        Date date=new Date();
        SimpleDateFormat curDate=new SimpleDateFormat("yyyy-MM-dd");
        String newDate=curDate.format(date);
        datelbl.setText(newDate);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        CIDtxt = new javax.swing.JTextField();
        timelbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/backButton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 920, 150, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/nextButton.png"))); // NOI18N
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 920, 150, 50));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(":");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 20, 50));

        datelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        datelbl.setForeground(new java.awt.Color(255, 255, 255));
        datelbl.setText("16");
        jPanel1.add(datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, 320, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer ID", "First Name", "Last Name" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 240, 40));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-vertical-line.png"))); // NOI18N
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 20, 30, 90));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Find Customer");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 450, 70));

        CIDtxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIDtxtActionPerformed(evt);
            }
        });
        CIDtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CIDtxtKeyReleased(evt);
            }
        });
        jPanel1.add(CIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 430, -1));

        timelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        timelbl.setForeground(new java.awt.Color(255, 255, 255));
        timelbl.setText("08:16:00");
        jPanel1.add(timelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 20, 360, 90));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CID", "First Name", "Last Name", "Age", "NIC", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 1660, 490));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Details");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 880, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-horizontal-line.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1910, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1060));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1060));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1060));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1920, 1060));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1060));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1060));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/istock000003037994medium.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 1100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Homepage h1 = new Homepage();
        mainPanel.removeAll();
        mainPanel.add(h1);
        h1.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int selRow=jTable1.getSelectedRow();
        String CID=(String) jTable1.getValueAt(selRow, 0);
        String fName=(String) jTable1.getValueAt(selRow, 1);
        String lName=(String) jTable1.getValueAt(selRow, 2);
        try {
            BlacklistCustomerModel bl= BlacklistcustomerController.searchCustomer(CID);
            if(bl == null){
                OpenAnAccount a1 = new OpenAnAccount();
                mainPanel.removeAll();
                mainPanel.add(a1);
                a1.setVisible(true);
            
                a1.txtId.setText(CID);
                a1.txtName.setText(fName+" "+lName);
                a1.txtDate.setText(datelbl.getText());
            }else{
                JOptionPane.showMessageDialog(this, "This Customer is Blacklisted Customer..!!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ExistingCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ExistingCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
           
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIDtxtActionPerformed
       
    }//GEN-LAST:event_CIDtxtActionPerformed

    private void CIDtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CIDtxtKeyReleased
        jButton2.setEnabled(true);
        String what = null;
        String which = null;
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        if (jComboBox1.getSelectedItem().equals("Customer ID")) {
            what = "CID";
            which = CIDtxt.getText();

            try {
                ArrayList<CustomerModel> cstList = CustomerController.searchCustomerArray(what, which);
                dtm.setRowCount(0);
                for (CustomerModel cst:cstList) {
                    String CID = cst.getCID();
                    String fName = cst.getfName();
                    String lName = cst.getlName();
                    String age = cst.getAge();
                    String NIC = cst.getNIC();
                    String occ = cst.getOccupation();
                    Object[] row = {CID, fName, lName, age, NIC, occ};
                    dtm.addRow(row);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ExistingCustomer.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ExistingCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else  if (jComboBox1.getSelectedItem().equals("First Name")) {
                what = "fName";
                which = CIDtxt.getText();

                try {
                    ArrayList<CustomerModel> cstList = CustomerController.searchCustomerArray(what, which);
                    dtm.setRowCount(0);
                    for (CustomerModel cst : cstList) {
                        String CID = cst.getCID();
                        String fName = cst.getfName();
                        String lName = cst.getlName();
                        String age = cst.getAge();
                        String NIC = cst.getNIC();
                        String occ = cst.getOccupation();
                        Object[] row = {CID, fName, lName, age, NIC, occ};
                        dtm.addRow(row);
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ExistingCustomer.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(ExistingCustomer.class.getName()).log(Level.SEVERE, null, ex);
                }
        }else{
                what = "lName";
                which = CIDtxt.getText();

                try {
                    ArrayList<CustomerModel> cstList = CustomerController.searchCustomerArray(what, which);
                    dtm.setRowCount(0);
                    for (CustomerModel cst : cstList) {
                        String CID = cst.getCID();
                        String fName = cst.getfName();
                        String lName = cst.getlName();
                        String age = cst.getAge();
                        String NIC = cst.getNIC();
                        String occ = cst.getOccupation();
                        Object[] row = {CID, fName, lName, age, NIC, occ};
                        dtm.addRow(row);
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ExistingCustomer.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(ExistingCustomer.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
    }//GEN-LAST:event_CIDtxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CIDtxt;
    private javax.swing.JLabel datelbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel timelbl;
    // End of variables declaration//GEN-END:variables
}
