/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankManagementSystem.View;

import All.IDgenerator;
import BankManagementSystem.Controller.AccountTypeController;
import BankManagementSystem.Controller.CustomerController;
import BankManagementSystem.Controller.GuarantorDetailsController;
import BankManagementSystem.Controller.LoanController;
import BankManagementSystem.Controller.LoanTypeController;
import BankManagementSystem.DBConnection.DBConnection;
import BankManagementSystem.Model.CustomerModel;
import BankManagementSystem.Model.GuarantorDetailsModel;
import BankManagementSystem.Model.LoanModel;
import BankManagementSystem.Model.LoanTypeModel;
import static BankManagementSystem.View.MainForm.mainPanel;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author NEOx
 */
public class GuarantDetails extends javax.swing.JInternalFrame {

    LoanModel m1;
    public static String custIdLast;
    public static String guarantID;

    /**
     * Creates new form GuarantDetails
     */
    public GuarantDetails() {
        initComponents();
        autoDate();
        autoTime();
        getID();
        txtLine.setVisible(false);
        jLabel51.setVisible(false);
        jLabel52.setVisible(false);
    }
    
    private void autoTime(){
        new Thread (new Runnable() {
            public void run (){
                while(true){
                    Date time = new Date();
                    String curDate=new SimpleDateFormat("hh:mm:ss aa").format(time);
                    timelbl.setText(curDate);
                    try{
                        Thread.sleep(1000);
                    }catch(InterruptedException ex){
                    
                    }
                }
            }
        }).start();

}
    private void autoDate(){
        Date date=new Date();
        SimpleDateFormat curDate=new SimpleDateFormat("yyyy-MM-dd");
        String newDate=curDate.format(date);
        datelbl.setText(newDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCertificateNo = new javax.swing.JTextField();
        txtValueOfHouse = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtValueOfLand = new javax.swing.JTextField();
        txtPresentOwner = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAdrs1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtLine = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        timelbl = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtDetails1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAdrs = new javax.swing.JTextArea();
        txtOccupation = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 1010, 730));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 820, 730));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Certificate No.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, 250, 50));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(":");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 240, 20, 50));

        txtCertificateNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCertificateNo.setBorder(null);
        txtCertificateNo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCertificateNo.setFocusTraversalPolicyProvider(true);
        txtCertificateNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCertificateNoActionPerformed(evt);
            }
        });
        txtCertificateNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCertificateNoKeyReleased(evt);
            }
        });
        jPanel1.add(txtCertificateNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 250, 430, 40));

        txtValueOfHouse.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtValueOfHouse.setBorder(null);
        txtValueOfHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueOfHouseActionPerformed(evt);
            }
        });
        txtValueOfHouse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValueOfHouseKeyReleased(evt);
            }
        });
        jPanel1.add(txtValueOfHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 330, 430, 40));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText(":");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 320, 20, 50));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Estimated Value of house");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, 430, 70));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Estimate Value of Land");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, 370, 70));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(":");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 400, 20, 50));

        txtValueOfLand.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtValueOfLand.setBorder(null);
        txtValueOfLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueOfLandActionPerformed(evt);
            }
        });
        txtValueOfLand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValueOfLandKeyReleased(evt);
            }
        });
        jPanel1.add(txtValueOfLand, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 410, 430, 40));

        txtPresentOwner.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPresentOwner.setBorder(null);
        txtPresentOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresentOwnerActionPerformed(evt);
            }
        });
        txtPresentOwner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPresentOwnerKeyReleased(evt);
            }
        });
        jPanel1.add(txtPresentOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 490, 430, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText(":");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 480, 20, 50));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Name of present owner");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, 400, 50));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Property");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 140, 450, 70));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-vertical-line.png"))); // NOI18N
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, 30, 720));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/backButton.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 920, 150, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Customer ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 210, 50));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(":");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 20, 50));

        txtId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdKeyReleased(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 430, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-vertical-line.png"))); // NOI18N
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 30, 30, 80));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Guarant");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 210, 50));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(":");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 20, 50));

        txtFName.setEditable(false);
        txtFName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 430, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText(":");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 20, 50));

        datelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        datelbl.setForeground(new java.awt.Color(255, 255, 255));
        datelbl.setText("16");
        jPanel1.add(datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, 320, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Address of the property");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 390, 70));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText(":");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 550, 20, 50));

        txtAdrs1.setColumns(20);
        txtAdrs1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        txtAdrs1.setRows(5);
        txtAdrs1.setBorder(null);
        txtAdrs1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdrs1KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(txtAdrs1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 560, 430, 190));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Age");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 210, 50));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText(":");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 20, 50));

        txtLine.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtLine.setForeground(new java.awt.Color(255, 255, 255));
        txtLine.setText("_______________________________");
        txtLine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtLineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtLineMouseExited(evt);
            }
        });
        jPanel1.add(txtLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 820, 510, 40));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Occupation");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 210, 50));

        timelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        timelbl.setForeground(new java.awt.Color(255, 255, 255));
        timelbl.setText("08:16:00");
        jPanel1.add(timelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 20, 360, 90));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText(":");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 20, 50));

        txtDetails1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtDetails1.setForeground(new java.awt.Color(255, 255, 255));
        txtDetails1.setText("Guarantor Accounts and Loan Details");
        txtDetails1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDetails1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDetails1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDetails1MouseExited(evt);
            }
        });
        jPanel1.add(txtDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 810, 510, 50));

        txtAdrs.setEditable(false);
        txtAdrs.setColumns(20);
        txtAdrs.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        txtAdrs.setRows(5);
        jScrollPane2.setViewportView(txtAdrs);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 430, 190));

        txtOccupation.setEditable(false);
        txtOccupation.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 430, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Name");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 210, 70));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Address");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 210, 70));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Guarantor ");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 240, 70));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/confirmButton.png"))); // NOI18N
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 920, 150, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Give a Loan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 880, 80));

        txtAge.setEditable(false);
        txtAge.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 430, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-horizontal-line.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1910, 40));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/istock000003037994medium.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 1100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LoanChooseAccount lca1=new LoanChooseAccount();
        mainPanel.removeAll();
        mainPanel.add(lca1);
        lca1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
         String CID = txtId.getText();
        try {
            CustomerModel cst=CustomerController.searchCustomer(CID);
            if(cst != null){
                txtId.setText(cst.getCID());
                txtFName.setText(cst.getfName()+" "+cst.getlName());
                txtAge.setText(cst.getAge());
                txtOccupation.setText(cst.getOccupation());
                txtAdrs.setText(cst.getAddress());
                
            }else{
                JOptionPane.showMessageDialog(this, "Customer ID is incorrect....");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoanFindCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LoanFindCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(txtOccupation.getText().trim().length()>0){
            jButton6.setEnabled(true);
        }
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtLineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLineMouseEntered
        
    }//GEN-LAST:event_txtLineMouseEntered

    private void txtDetails1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDetails1MouseEntered
        txtLine.setVisible(true);
    }//GEN-LAST:event_txtDetails1MouseEntered

    private void txtLineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLineMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLineMouseExited

    private void txtDetails1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDetails1MouseExited
        txtLine.setVisible(false);
    }//GEN-LAST:event_txtDetails1MouseExited

    private void txtCertificateNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCertificateNoActionPerformed
        txtValueOfHouse.requestFocus();
    }//GEN-LAST:event_txtCertificateNoActionPerformed

    private void txtValueOfHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueOfHouseActionPerformed
        txtValueOfLand.requestFocus();
    }//GEN-LAST:event_txtValueOfHouseActionPerformed

    private void txtValueOfLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueOfLandActionPerformed
        txtPresentOwner.requestFocus();
    }//GEN-LAST:event_txtValueOfLandActionPerformed

    private void txtPresentOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresentOwnerActionPerformed
        
    }//GEN-LAST:event_txtPresentOwnerActionPerformed
    double interest;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       try {
            boolean res1=LoanController.addLoan(m1);
            if(res1){
                JOptionPane.showMessageDialog(this, "Loan giving Successfull....");
                Homepage h1 = new Homepage();
                String LID=m1.getLID();
                String period=m1.getDuration();
                double amount = m1.getAmount();
                double monthlyInstallment =m1.getPeriodical();
                
                
                InputStream is=getClass().getResourceAsStream("RecieptLoan.jrxml");
                JasperReport jp = JasperCompileManager.compileReport(is);
                HashMap hm=new HashMap();
                hm.put("LID",LID);
                hm.put("period",period);
                hm.put("amount",amount);
                hm.put("interest",interest);
                hm.put("monthlyInstallment",monthlyInstallment);
                JasperPrint jsp=JasperFillManager.fillReport(jp,hm,new JREmptyDataSource());
                JasperViewer.viewReport(jsp);
                
                
                mainPanel.removeAll();
                mainPanel.add(h1);
                h1.setVisible(true);
                
            }else{
                JOptionPane.showMessageDialog(this, "Loan giving Failed....");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GuarantDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GuarantDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(GuarantDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        String CID=null;
        if(txtId.getText().trim().length()==0){
            CID=custIdLast;
        }else{
            CID=txtId.getText();
        }
        
        
        String certificateNo=txtCertificateNo.getText();
        double valueOfHouse=0;
        if(txtValueOfHouse.getText().trim().length()!=0){
            valueOfHouse=Double.parseDouble(txtValueOfHouse.getText());
        }
            CID=txtId.getText();
    
        double valueOfLand=0;
        if(txtValueOfHouse.getText().trim().length()!=0){
            valueOfLand=Double.parseDouble(txtValueOfLand.getText());
        }
        String ownerName=txtPresentOwner.getText();
        String address=txtAdrs1.getText();
        String LID =m1.getLID();
        System.out.println(LID);
        GuarantorDetailsModel g1=new GuarantorDetailsModel(guarantID,LID,custIdLast ,certificateNo, valueOfHouse, valueOfLand, ownerName, address);
        
       try {
            GuarantorDetailsController.addGuarantorDetails(g1);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GuarantDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GuarantDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtCertificateNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCertificateNoKeyReleased
        if(txtCertificateNo.getText().length()>0){
           jLabel51.setVisible(true);
           txtId.setEditable(false);
        }else{
            jLabel51.setVisible(false);
            txtId.setEditable(true);
        }
    }//GEN-LAST:event_txtCertificateNoKeyReleased

    private void txtIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyReleased
         if(txtId.getText().length()>0){
           jLabel52.setVisible(true);
           txtCertificateNo.setEditable(false);
           txtValueOfHouse.setEditable(false);
           txtValueOfLand.setEditable(false);
           txtPresentOwner.setEditable(false);
          
        }else{
           jLabel52.setVisible(false);
           txtCertificateNo.setEditable(true);
           txtValueOfHouse.setEditable(true);
           txtValueOfLand.setEditable(true);
           txtPresentOwner.setEditable(true);
           
        }
    }//GEN-LAST:event_txtIdKeyReleased

    private void txtAdrs1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdrs1KeyReleased
        jButton6.setEnabled(true);
    }//GEN-LAST:event_txtAdrs1KeyReleased

    private void txtValueOfHouseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValueOfHouseKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.limitesIntegers(txtValueOfHouse,7);
        }
    }//GEN-LAST:event_txtValueOfHouseKeyReleased

    private void txtValueOfLandKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValueOfLandKeyReleased
         if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.numberOnly(txtValueOfLand);
        }
    }//GEN-LAST:event_txtValueOfLandKeyReleased

    private void txtPresentOwnerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPresentOwnerKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.name(txtPresentOwner);
        }
    }//GEN-LAST:event_txtPresentOwnerKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datelbl;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel timelbl;
    private javax.swing.JTextArea txtAdrs;
    private javax.swing.JTextArea txtAdrs1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCertificateNo;
    private javax.swing.JLabel txtDetails1;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtId;
    private javax.swing.JLabel txtLine;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtPresentOwner;
    private javax.swing.JTextField txtValueOfHouse;
    private javax.swing.JTextField txtValueOfLand;
    // End of variables declaration//GEN-END:variables
    
    public  void getID(){
       String newID;
        try {
            newID=IDgenerator.autoID("guarantDetails", "GuarantID", "G");
            guarantID=newID;
        } catch (SQLException ex) {
            Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }

}
