/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankManagementSystem.View;

import static BankManagementSystem.View.MainForm.mainPanel;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author NEOx
 */
public class Homepage extends javax.swing.JInternalFrame {

    /**
     * Creates new form Home
     */
    public Homepage() {
        initComponents();
        autoTime();
        autoDate();
       
    }
    
    private void autoTime(){
    new Thread (new Runnable() {
        public void run (){
            while(true){
                Date time = new Date();
                String curDate=new SimpleDateFormat("hh:mm:ss aa").format(time);
                timelbl.setText(curDate);
                try{
                    Thread.sleep(1000);
                }catch(InterruptedException ex){
                    
                }
            }
        }
    }).start();
   }
    
    private void autoDate(){
        Date date=new Date();
        SimpleDateFormat curDate=new SimpleDateFormat("yyyy-MM-dd");
        String newDate=curDate.format(date);
        datelbl.setText(newDate);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        backupBt = new javax.swing.JButton();
        manageAcccount = new javax.swing.JButton();
        settlePaymentbt = new javax.swing.JButton();
        datelbl = new javax.swing.JLabel();
        giveALonebt = new javax.swing.JButton();
        manageCustomerbt = new javax.swing.JButton();
        moneyTransactionbt = new javax.swing.JButton();
        openAccountbt = new javax.swing.JButton();
        viewReportsbt1 = new javax.swing.JButton();
        timelbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-vertical-line.png"))); // NOI18N
        jPanel1.add(jLabel34);
        jLabel34.setBounds(1490, 30, 38, 80);

        backupBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/backup.jpg"))); // NOI18N
        backupBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backupBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backupBtMouseExited(evt);
            }
        });
        backupBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupBtActionPerformed(evt);
            }
        });
        jPanel1.add(backupBt);
        backupBt.setBounds(440, 720, 290, 290);

        manageAcccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/manageAccount.jpg"))); // NOI18N
        manageAcccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageAcccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageAcccountMouseExited(evt);
            }
        });
        manageAcccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAcccountActionPerformed(evt);
            }
        });
        jPanel1.add(manageAcccount);
        manageAcccount.setBounds(730, 430, 580, 290);

        settlePaymentbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/settlePayment.jpg"))); // NOI18N
        settlePaymentbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settlePaymentbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settlePaymentbtMouseExited(evt);
            }
        });
        settlePaymentbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settlePaymentbtActionPerformed(evt);
            }
        });
        settlePaymentbt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                settlePaymentbtKeyPressed(evt);
            }
        });
        jPanel1.add(settlePaymentbt);
        settlePaymentbt.setBounds(1310, 140, 290, 290);

        datelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        datelbl.setForeground(new java.awt.Color(255, 255, 255));
        datelbl.setText("16");
        jPanel1.add(datelbl);
        datelbl.setBounds(1180, 20, 320, 90);

        giveALonebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/giveALoan.jpg"))); // NOI18N
        giveALonebt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                giveALonebtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                giveALonebtMouseExited(evt);
            }
        });
        giveALonebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveALonebtActionPerformed(evt);
            }
        });
        jPanel1.add(giveALonebt);
        giveALonebt.setBounds(1020, 140, 290, 290);

        manageCustomerbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/manageCustomer.jpg"))); // NOI18N
        manageCustomerbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageCustomerbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageCustomerbtMouseExited(evt);
            }
        });
        manageCustomerbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerbtActionPerformed(evt);
            }
        });
        jPanel1.add(manageCustomerbt);
        manageCustomerbt.setBounds(150, 430, 580, 290);

        moneyTransactionbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/moneyTransaction1.jpg"))); // NOI18N
        moneyTransactionbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moneyTransactionbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moneyTransactionbtMouseExited(evt);
            }
        });
        moneyTransactionbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyTransactionbtActionPerformed(evt);
            }
        });
        jPanel1.add(moneyTransactionbt);
        moneyTransactionbt.setBounds(440, 140, 580, 290);

        openAccountbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/openAnAccount.jpg"))); // NOI18N
        openAccountbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                openAccountbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                openAccountbtMouseExited(evt);
            }
        });
        openAccountbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAccountbtActionPerformed(evt);
            }
        });
        openAccountbt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                openAccountbtKeyPressed(evt);
            }
        });
        jPanel1.add(openAccountbt);
        openAccountbt.setBounds(150, 140, 290, 290);

        viewReportsbt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/viewReports.jpg"))); // NOI18N
        viewReportsbt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewReportsbt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewReportsbt1MouseExited(evt);
            }
        });
        viewReportsbt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportsbt1ActionPerformed(evt);
            }
        });
        jPanel1.add(viewReportsbt1);
        viewReportsbt1.setBounds(150, 720, 290, 290);

        timelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        timelbl.setForeground(new java.awt.Color(255, 255, 255));
        timelbl.setText("08:16:00");
        jPanel1.add(timelbl);
        timelbl.setBounds(1520, 20, 360, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/userIcon.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 20, 80, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-horizontal-line.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 100, 1910, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USER");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 30, 110, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/logOut.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 60, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1910, 1070);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 1910, 1070);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 0, 1910, 1070);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, 0, 1910, 1070);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(0, 0, 1910, 1070);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/istock000003037994medium.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 1920, 1100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1904, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settlePaymentbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settlePaymentbtActionPerformed
       SettlePayment1 sp1 = new SettlePayment1();
       mainPanel.removeAll();
       mainPanel.add(sp1);
       sp1.setVisible(true);
    }//GEN-LAST:event_settlePaymentbtActionPerformed

    private void giveALonebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveALonebtActionPerformed
        LoanFindCustomer lc1=new LoanFindCustomer();
        mainPanel.removeAll();
        mainPanel.add(lc1);
        lc1.setVisible(true);
    }//GEN-LAST:event_giveALonebtActionPerformed

    private void moneyTransactionbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyTransactionbtActionPerformed
        MoneyTransactionMenu m1 = new MoneyTransactionMenu();
        mainPanel.removeAll();
        mainPanel.add(m1);
        m1.setVisible(true);
    }//GEN-LAST:event_moneyTransactionbtActionPerformed

    private void openAccountbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openAccountbtMouseEntered
         openAccountbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/openAnAccountSel.jpg")));
    }//GEN-LAST:event_openAccountbtMouseEntered

    private void openAccountbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openAccountbtMouseExited
        openAccountbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/openAnAccount.jpg")));
    }//GEN-LAST:event_openAccountbtMouseExited

    private void openAccountbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAccountbtActionPerformed
        CustomerRegistration c1 = new CustomerRegistration();
        mainPanel.removeAll();
        mainPanel.add(c1);
        c1.setVisible(true);
    }//GEN-LAST:event_openAccountbtActionPerformed

    private void viewReportsbt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportsbt1ActionPerformed
        ViewReportMenu vr=new ViewReportMenu();
        mainPanel.removeAll();
        mainPanel.add(vr);
        vr.setVisible(true);
    }//GEN-LAST:event_viewReportsbt1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Loginpage l1 = new Loginpage();
        mainPanel.removeAll();
        mainPanel.add(l1);
        l1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void moneyTransactionbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyTransactionbtMouseEntered
        moneyTransactionbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/moneyTransaction1Sel.jpg")));
    }//GEN-LAST:event_moneyTransactionbtMouseEntered

    private void moneyTransactionbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyTransactionbtMouseExited
        moneyTransactionbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/moneyTransaction1.jpg")));
    }//GEN-LAST:event_moneyTransactionbtMouseExited

    private void giveALonebtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giveALonebtMouseEntered
        giveALonebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/giveALoanSel.jpg")));
    }//GEN-LAST:event_giveALonebtMouseEntered

    private void giveALonebtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giveALonebtMouseExited
        giveALonebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/giveALoan.jpg")));
    }//GEN-LAST:event_giveALonebtMouseExited

    private void settlePaymentbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settlePaymentbtMouseEntered
        settlePaymentbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/settlePaymentSel.jpg")));
    }//GEN-LAST:event_settlePaymentbtMouseEntered

    private void settlePaymentbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settlePaymentbtMouseExited
        settlePaymentbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/settlePayment.jpg")));
    }//GEN-LAST:event_settlePaymentbtMouseExited

    private void manageCustomerbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageCustomerbtMouseEntered
        manageCustomerbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/manageCustomerSel.jpg")));
    }//GEN-LAST:event_manageCustomerbtMouseEntered

    private void manageCustomerbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageCustomerbtMouseExited
        manageCustomerbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/manageCustomer.jpg")));
    }//GEN-LAST:event_manageCustomerbtMouseExited

    private void viewReportsbt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewReportsbt1MouseEntered
        viewReportsbt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/viewReportsSel.jpg")));
    }//GEN-LAST:event_viewReportsbt1MouseEntered

    private void viewReportsbt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewReportsbt1MouseExited
        viewReportsbt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/viewReports.jpg")));
    }//GEN-LAST:event_viewReportsbt1MouseExited

    private void openAccountbtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_openAccountbtKeyPressed

    }//GEN-LAST:event_openAccountbtKeyPressed

    private void settlePaymentbtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_settlePaymentbtKeyPressed
    
    }//GEN-LAST:event_settlePaymentbtKeyPressed

    private void manageCustomerbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerbtActionPerformed
        ManageCustomerMenu mc1=new ManageCustomerMenu();
        mainPanel.removeAll();
        mainPanel.add(mc1);
        mc1.setVisible(true);
    }//GEN-LAST:event_manageCustomerbtActionPerformed

    private void manageAcccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAcccountMouseEntered
        manageAcccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/manageAccountSel.jpg")));
    }//GEN-LAST:event_manageAcccountMouseEntered

    private void manageAcccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAcccountMouseExited
        manageAcccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/manageAccount.jpg")));
    }//GEN-LAST:event_manageAcccountMouseExited

    private void manageAcccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAcccountActionPerformed
        ManageAccountMenu ma=new ManageAccountMenu();
        mainPanel.removeAll();
        mainPanel.add(ma);
        ma.setVisible(true);
    }//GEN-LAST:event_manageAcccountActionPerformed

    private void backupBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backupBtMouseEntered
        backupBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/backupSel.jpg")));
    }//GEN-LAST:event_backupBtMouseEntered

    private void backupBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backupBtMouseExited
        backupBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/backup.jpg")));
    }//GEN-LAST:event_backupBtMouseExited

    private void backupBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backupBtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backupBt;
    private javax.swing.JLabel datelbl;
    private javax.swing.JButton giveALonebt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageAcccount;
    private javax.swing.JButton manageCustomerbt;
    private javax.swing.JButton moneyTransactionbt;
    private javax.swing.JButton openAccountbt;
    private javax.swing.JButton settlePaymentbt;
    private javax.swing.JLabel timelbl;
    private javax.swing.JButton viewReportsbt1;
    // End of variables declaration//GEN-END:variables
}
