/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankManagementSystem.View;

import All.IDgenerator;
import BankManagementSystem.Controller.LoanTypeController;
import BankManagementSystem.Model.LoanModel;
import BankManagementSystem.Model.LoanTypeModel;
import static BankManagementSystem.View.MainForm.mainPanel;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author NEOx
 */
public class LoanDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form LoanDetails
     */
    public static String AID;
    
    public LoanDetails() {
        initComponents();
        autoDate();
        autoTime();
        getID();
        txtDate.setText(datelbl.getText());
        LA.setVisible(false);
        I.setVisible(false);
        MI.setVisible(false);
        x1.setVisible(false);
        x2.setVisible(false);
        x3.setVisible(false);
        lblLoanAmount.setVisible(false);
        lblinterest.setVisible(false);
        lblMonthlyInstallment.setVisible(false);
    }
    
    
    private void autoTime(){
    new Thread (new Runnable() {
        public void run (){
            while(true){
                Date time = new Date();
                String curDate=new SimpleDateFormat("hh:mm:ss aa").format(time);
                timelbl.setText(curDate);
                try{
                    Thread.sleep(1000);
                }catch(InterruptedException ex){
                    
                }
            }
        }
    }).start();

}
     private void autoDate(){
        Date date=new Date();
        SimpleDateFormat curDate=new SimpleDateFormat("yyyy-MM-dd");
        String newDate=curDate.format(date);
        datelbl.setText(newDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        timelbl = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        x2 = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        x3 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtLoanAmount = new javax.swing.JTextField();
        txtLoanId = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        lblLoanAmount = new javax.swing.JLabel();
        lblinterest = new javax.swing.JLabel();
        lblMonthlyInstallment = new javax.swing.JLabel();
        LA = new javax.swing.JLabel();
        txtPeriod = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReason = new javax.swing.JTextArea();
        txtAmountInWords = new javax.swing.JTextField();
        txtLoanType = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        MI = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        I = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/backButton.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 920, 150, 50));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-vertical-line.png"))); // NOI18N
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 30, 30, 80));

        datelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        datelbl.setForeground(new java.awt.Color(255, 255, 255));
        datelbl.setText("16");
        jPanel1.add(datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, 320, -1));

        timelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        timelbl.setForeground(new java.awt.Color(255, 255, 255));
        timelbl.setText("08:16:00");
        jPanel1.add(timelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 20, 360, 90));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Loan Details");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 450, 70));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Loan Type ");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 210, 50));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText(":");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 20, 50));

        x2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        x2.setForeground(new java.awt.Color(255, 255, 255));
        x2.setText(":");
        jPanel1.add(x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 620, 20, 50));

        x1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        x1.setForeground(new java.awt.Color(255, 255, 255));
        x1.setText(":");
        jPanel1.add(x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 570, 20, 50));

        x3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        x3.setForeground(new java.awt.Color(255, 255, 255));
        x3.setText(":");
        jPanel1.add(x3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 670, 20, 50));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Loan Amount");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 250, 50));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Repayment Period");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 290, 50));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText(":");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 20, 50));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText(":");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 20, 50));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Loan ID");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 250, 50));

        txtLoanAmount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtLoanAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoanAmountActionPerformed(evt);
            }
        });
        txtLoanAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLoanAmountKeyReleased(evt);
            }
        });
        jPanel1.add(txtLoanAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 430, -1));

        txtLoanId.setEditable(false);
        txtLoanId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtLoanId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoanIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtLoanId, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 430, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Amount in words");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 260, 50));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText(":");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, 20, 50));

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Rupees");
        jPanel1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 500, 90, 50));

        lblLoanAmount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLoanAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblLoanAmount.setText("Loan Amount");
        jPanel1.add(lblLoanAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 570, 180, 50));

        lblinterest.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblinterest.setForeground(new java.awt.Color(255, 255, 255));
        lblinterest.setText("Interest");
        jPanel1.add(lblinterest, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 620, 180, 50));

        lblMonthlyInstallment.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblMonthlyInstallment.setForeground(new java.awt.Color(255, 255, 255));
        lblMonthlyInstallment.setText("Monthly Instalment");
        jPanel1.add(lblMonthlyInstallment, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 670, 290, 50));

        LA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LA.setForeground(new java.awt.Color(255, 255, 255));
        LA.setText("Loan Amount");
        jPanel1.add(LA, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 570, 180, 50));

        txtPeriod.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtPeriod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Year", "2 Years", "3 Years", "4 Years", "5 Years", "6 Years", "7 Years", "8 Years", "9 Years", "10 Years" }));
        txtPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeriodActionPerformed(evt);
            }
        });
        jPanel1.add(txtPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 300, 40));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Reason");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 290, 50));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText(":");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 660, 20, 50));

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Rupees");
        jPanel1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 580, 90, 50));

        txtReason.setColumns(20);
        txtReason.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        txtReason.setRows(5);
        txtReason.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReasonKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txtReason);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 670, 430, 190));

        txtAmountInWords.setEditable(false);
        txtAmountInWords.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtAmountInWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountInWordsActionPerformed(evt);
            }
        });
        jPanel1.add(txtAmountInWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, 700, -1));

        txtLoanType.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtLoanType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Housing", "Leasing", "Saviya" }));
        txtLoanType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoanTypeActionPerformed(evt);
            }
        });
        jPanel1.add(txtLoanType, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 300, 40));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText(":");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 240, 20, 50));

        MI.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        MI.setForeground(new java.awt.Color(255, 255, 255));
        MI.setText("Monthly Instalment");
        jPanel1.add(MI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 670, 290, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/nextButton.png"))); // NOI18N
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 920, 150, 50));

        I.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        I.setForeground(new java.awt.Color(255, 255, 255));
        I.setText("Interest");
        jPanel1.add(I, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 620, 180, 50));

        txtDate.setEditable(false);
        txtDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 250, 430, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Date");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 240, 130, 50));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText(":");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 20, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Make a Loan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 880, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-horizontal-line.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1910, 40));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/istock000003037994medium.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 1100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LoanChooseAccount lc1 =new LoanChooseAccount();
        mainPanel.removeAll();
        mainPanel.add(lc1);
        lc1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtLoanIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoanIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoanIdActionPerformed

    private void txtLoanAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoanAmountActionPerformed
        String loanType=(String) txtLoanType.getSelectedItem();
        double amount=Double.parseDouble(txtLoanAmount.getText());
        double rate=0;
        int year = 0;
        int month=0;
        if(loanType.equals("Normal")){
            rate=0.02;
        }else if(loanType.equals("Housing")){
            rate=0.1;
        }else if(loanType.equals("Leasing")){
            rate=0.05;
        }else{
            rate=0.025;
        }
        
        String period=(String) txtPeriod.getSelectedItem();
        if(period.equals("1 Year")){
            year=1;
            month=12;
        }else if(period.equals("2 Years")){
            year=2;
            month=24;
        }else if(period.equals("3 Years")){
            year=3;
            month=36;
        }else if(period.equals("4 Years")){
            year=4;
            month=48;
        }else if(period.equals("5 Years")){
            year=5;
            month=60;
        }else if(period.equals("6 Years")){
            year=6;
            month=72;
        }else if(period.equals("7 Years")){
            year=7;
            month=84;
        }else if(period.equals("8 Years")){
            year=8;
            month=96;
        }else if(period.equals("9 Years")){
            year=9;
            month=108;
        }else if(period.equals("10 Years")){
            year=10;
            month=120;
        }
        
        double interest = ((amount * rate)*year)/month;
        double instalmentAmount=amount/month;
        String monthlyInstalment=Double.toString(interest+instalmentAmount);      
        lblLoanAmount.setText(Double.toString(amount));
        lblinterest.setText(Double.toString(interest*month));
        lblMonthlyInstallment.setText(monthlyInstalment);
        System.out.println(interest);
        System.out.println(loanType);
        System.out.println(year);
        
        LA.setVisible(true);
        I.setVisible(true);
        MI.setVisible(true);
        x1.setVisible(true);
        x2.setVisible(true);
        x3.setVisible(true);
        lblLoanAmount.setVisible(true);
        lblinterest.setVisible(true);
        lblMonthlyInstallment.setVisible(true);
        
        txtAmountInWords.setText(convert((int) amount));
        txtReason.requestFocus();
    }//GEN-LAST:event_txtLoanAmountActionPerformed

    private void txtAmountInWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountInWordsActionPerformed
        jButton3.setEnabled(true);
    }//GEN-LAST:event_txtAmountInWordsActionPerformed

    private void txtPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeriodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeriodActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtLoanTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoanTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoanTypeActionPerformed
    
    public static String custId2;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String loanId=txtLoanId.getText();
        String loanType=(String) txtLoanType.getSelectedItem();
        String loanTypeName=null;
        try {
            LoanTypeModel lt1=LoanTypeController.searchLoanTypeName(loanType);
            loanTypeName=lt1.getLONTID();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoanDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LoanDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String period=(String) txtPeriod.getSelectedItem();
        double loanAmount=Double.parseDouble(txtLoanAmount.getText());
        String reason=txtReason.getText();
        String date=txtDate.getText();
        double monthmyInstalment=Double.parseDouble(lblMonthlyInstallment.getText());
        
        LoanModel lm1=new LoanModel(loanId, AID, reason, loanTypeName,period, date, loanAmount, monthmyInstalment, loanAmount);
        
        GuarantDetails g1 = new GuarantDetails();
        g1.m1=lm1;
        g1.custIdLast=custId2;
        g1.interest=Double.parseDouble(lblinterest.getText());
        mainPanel.removeAll();
        mainPanel.add(g1);
        g1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtReasonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReasonKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.Reason(txtReason);
        }
        
        if(txtAmountInWords.getText().trim().length()>0){
            jButton2.setEnabled(true);
        }
    }//GEN-LAST:event_txtReasonKeyReleased

    private void txtLoanAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoanAmountKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.limitesIntegers(txtLoanAmount, 7);
        }      
    }//GEN-LAST:event_txtLoanAmountKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel I;
    private javax.swing.JLabel LA;
    private javax.swing.JLabel MI;
    private javax.swing.JLabel datelbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLoanAmount;
    private javax.swing.JLabel lblMonthlyInstallment;
    private javax.swing.JLabel lblinterest;
    private javax.swing.JLabel timelbl;
    private javax.swing.JTextField txtAmountInWords;
    public static javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtLoanAmount;
    public static javax.swing.JTextField txtLoanId;
    private javax.swing.JComboBox<String> txtLoanType;
    private javax.swing.JComboBox<String> txtPeriod;
    private javax.swing.JTextArea txtReason;
    private javax.swing.JLabel x1;
    private javax.swing.JLabel x2;
    private javax.swing.JLabel x3;
    // End of variables declaration//GEN-END:variables
    public  void getID(){
       String newID;
        try {
            newID=IDgenerator.autoID("loan", "LID", "L");
            txtLoanId.setText(newID);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }
private String oneToHundred(int amount){
        String a1=" ";
        while( amount!=0){
            if(amount==1){
                a1=a1+"One";
                amount=0;
            }else if( amount ==2 ){
                a1=a1+"Two";
                amount=0;
            }else if( amount ==3 ){
                a1=a1+"Three";
                amount=0;
            }else if( amount ==4 ){
                a1=a1+"Four";
                amount=0;
            }else if( amount ==5 ){
                a1=a1+"Five";
                amount=0;
            }else if( amount ==6 ){
                a1=a1+"Six";
                amount=0;
            }else if( amount ==7 ){
                a1=a1+"Seven";
                amount=0;
            }else if( amount ==8 ){
                a1=a1+"Eight";
                amount=0;
            }else if( amount ==9 ){
                a1=a1+"Nine";
                amount=0;
            }else if( amount ==10 ){
                a1=a1+"Ten";
                amount=0;
            }else if( amount ==11 ){
                a1=a1+"Eleven";
                amount=0;
            }else if( amount ==12){
                a1=a1+"Twelve";
                amount=0;
            }else if( amount ==13){
                a1=a1+"Thirteen";
                amount=0;
            }else if( amount ==14){
                a1=a1+"Fourteen";
                amount=0;
            }else if( amount ==15){
                a1=a1+"Fifteen";
                amount=0;
            }else if( amount ==16){
                a1=a1+"Sixteen";
                amount=0;
            }else if( amount ==17){
                a1=a1+"Seventeen";
                amount=0;
            }else if( amount ==18){
                a1=a1+"Eighteen";
                amount=0;
            }else if( amount ==19){
                a1=a1+"Nineteen";
                amount=0;
            }else if(amount>=20 && amount <30){
                a1=a1+"Twenty ";
                amount=amount-20;
            }else if(amount>=30 && amount <40){
                a1=a1+"Thirty ";
                amount=amount-30;
            }else if(amount>=40 && amount <50){
                a1=a1+"Fourty ";
                amount=amount-40;
            }else if(amount>=50 && amount <60){
                a1=a1+"Fifty ";
                amount=amount-50;
            }else if(amount>=60 && amount <70){
                a1=a1+"Sixty ";
                amount=amount-60;
            }else if(amount>=70 && amount <80){
                a1=a1+"Seventy ";
                amount=amount-70;
            }else if(amount>=80 && amount <90){
                a1=a1+"Eighty ";
                amount=amount-80;
            }else if(amount>=90 && amount <100){
                a1=a1+"Ninety ";
                amount=amount-90;
            }
        }
        
        return a1;
    }

    private String convert(int amount){
        String a1=" ";
        
        while(amount != 0){
            if(amount >=1 && amount <100){
                a1=a1+oneToHundred(amount);
                amount=0;
            }else if(amount >= 100 && amount < 1000){
                a1=a1+oneToHundred(amount/100);
                a1=a1+" Hundred ";
                amount = amount % 100;
            }else if(amount >= 1000 && amount < 10000){
                a1=a1+oneToHundred(amount/1000);
                a1=a1+" Thousand";
                amount = amount % 1000;
            }else if(amount >= 10000 && amount < 100000){
                a1=a1+oneToHundred(amount/1000);
                a1=a1+" Thousand";
                amount = amount % 1000;
            }else if(amount >= 100000 && amount <10000000){
                a1=a1+oneToHundred(amount/100000);
                a1=a1+" Lakh";
                amount = amount % 100000;
            }
        }
        
        return a1;
    }

}
