/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankManagementSystem.View;

import static BankManagementSystem.View.MainForm.mainPanel;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author NEOx
 */
public class MoneyTransactionMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form MoneyTransactionMenu
     */
    public MoneyTransactionMenu() {
        initComponents();
        autoTime();
        autoDate();
    }
    private void autoDate(){
        Date date=new Date();
        SimpleDateFormat curDate=new SimpleDateFormat("yyyy-MM-dd");
        String newDate=curDate.format(date);
        datelbl.setText(newDate);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        datelbl = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        timelbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/backButton.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1720, 940, 150, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/depositx.jpg"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 290, 290));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/withdraw.jpg"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 290, 290));

        datelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        datelbl.setForeground(new java.awt.Color(255, 255, 255));
        datelbl.setText("16");
        jPanel1.add(datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, 320, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-vertical-line.png"))); // NOI18N
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 20, 30, 90));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Money Transactions");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 880, 80));

        timelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        timelbl.setForeground(new java.awt.Color(255, 255, 255));
        timelbl.setText("08:16:00");
        jPanel1.add(timelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 20, 360, 90));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-horizontal-line.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1910, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/istock000003037994medium.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 1100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Deposit d1 = new Deposit();
       mainPanel.removeAll();
       mainPanel.add(d1);
       d1.setVisible(true);
       d1.txtDate.setText(datelbl.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Withdraw w1 = new Withdraw();
       mainPanel.removeAll();
       mainPanel.add(w1);
       w1.setVisible(true);
       w1.txtDate.setText(datelbl.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Homepage h1 = new Homepage();
        mainPanel.removeAll();
        mainPanel.add(h1);
        h1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/withdrawSel.jpg")));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/withdraw.jpg")));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/depositxSel.jpg")));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/depositx.jpg")));
    }//GEN-LAST:event_jButton2MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datelbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel timelbl;
    // End of variables declaration//GEN-END:variables


private void autoTime(){
    new Thread (new Runnable() {
        public void run (){
            while(true){
                Date time = new Date();
                String curDate=new SimpleDateFormat("hh:mm:ss aa").format(time);
                timelbl.setText(curDate);
                try{
                    Thread.sleep(1000);
                }catch(InterruptedException ex){
                    
                }
            }
        }
    }).start();

}

}
