/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankManagementSystem.View;

import BankManagementSystem.Controller.AccountController;
import BankManagementSystem.Controller.CustomerController;
import BankManagementSystem.Controller.LoanController;
import BankManagementSystem.Controller.LoanTypeController;
import BankManagementSystem.Controller.PaymentController;
import BankManagementSystem.Model.AccountModel;
import BankManagementSystem.Model.CustomerModel;
import BankManagementSystem.Model.LoanModel;
import BankManagementSystem.Model.LoanTypeModel;
import BankManagementSystem.Model.PaymentModel;
import static BankManagementSystem.View.MainForm.mainPanel;
import static BankManagementSystem.View.SettlePayment2.LID;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NEOx
 */
public class SettlePayment1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public SettlePayment1() {
        initComponents();
        autoDate();
        autoTime();
    }
    
     private void autoTime(){
    new Thread (new Runnable() {
        public void run (){
            while(true){
                Date time = new Date();
                String curDate=new SimpleDateFormat("hh:mm:ss aa").format(time);
                timelbl.setText(curDate);
                try{
                    Thread.sleep(1000);
                }catch(InterruptedException ex){
                    
                }
            }
        }
    }).start();
   }
    
    private void autoDate(){
        Date date=new Date();
        SimpleDateFormat curDate=new SimpleDateFormat("yyyy-MM-dd");
        String newDate=curDate.format(date);
        datelbl.setText(newDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtLoanId = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        searchCombo = new javax.swing.JComboBox<>();
        txtAmountToBePaid = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtAccontId = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        datelbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        timelbl = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtLoanAmount = new javax.swing.JTextField();
        txtMonthlyInstalment = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLoanType = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Find Loan");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, 450, 70));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-vertical-line.png"))); // NOI18N
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 30, 780));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/backButton.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 920, 150, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Loan ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 210, 50));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(":");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 20, 50));

        txtLoanId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtLoanId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoanIdActionPerformed(evt);
            }
        });
        txtLoanId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLoanIdKeyReleased(evt);
            }
        });
        jPanel1.add(txtLoanId, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 430, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-vertical-line.png"))); // NOI18N
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 30, 30, 80));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Account ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 210, 70));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(":");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 20, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/nextButton.png"))); // NOI18N
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 920, 150, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-horizontal-line.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 830, 40));

        searchCombo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        searchCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account ID", "Customer Name" }));
        searchCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchComboActionPerformed(evt);
            }
        });
        jPanel1.add(searchCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 230, 260, 40));

        txtAmountToBePaid.setEditable(false);
        txtAmountToBePaid.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtAmountToBePaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 770, 430, -1));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 230, 400, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText(":");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 220, -1, 50));

        txtAccontId.setEditable(false);
        txtAccontId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtAccontId, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 430, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Customer Name");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 260, 70));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(":");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 20, 50));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText(":");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 760, 20, 50));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Amount to be Paid");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 750, 300, 70));

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 430, -1));

        datelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        datelbl.setForeground(new java.awt.Color(255, 255, 255));
        datelbl.setText("16");
        jPanel1.add(datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, 320, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Loan ID", "Account ID", "Customer Name", "Loan Type", "Loan Amount", "Monthly Installment", "Amount To Be Paid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 310, 940, 510));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Loan Type");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 210, 50));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText(":");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 20, 50));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Loan Amount");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 210, 50));

        timelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        timelbl.setForeground(new java.awt.Color(255, 255, 255));
        timelbl.setText("08:16:00");
        jPanel1.add(timelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 20, 360, 90));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText(":");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, 20, 50));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Monthly Installment");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, 310, 50));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(":");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 680, 20, 50));

        txtLoanAmount.setEditable(false);
        txtLoanAmount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtLoanAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 610, 430, -1));

        txtMonthlyInstalment.setEditable(false);
        txtMonthlyInstalment.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtMonthlyInstalment, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 690, 430, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Loan Details");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 450, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Settle Payment");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 880, 80));

        txtLoanType.setEditable(false);
        txtLoanType.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtLoanType, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 430, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-horizontal-line.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1910, 40));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1070));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/istock000003037994medium.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 1100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Homepage h1 = new Homepage();
        mainPanel.removeAll();
        mainPanel.add(h1);
        h1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtLoanIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoanIdActionPerformed
        String LID=txtLoanId.getText();
        try {
            LoanModel loan=LoanController.searchLoan(LID);
            if(loan != null){
                String AID = loan.getAID();
                AccountModel acount=AccountController.searchAccount(AID);
                String CID=acount.getCID();
                CustomerModel cst=CustomerController.searchCustomer(CID);
                String Name =cst.getfName()+" "+cst.getlName();
                String lnType=loan.getLoanType();
                LoanTypeModel lnModel=LoanTypeController.searchLoanType(lnType);
                String loanType=lnModel.getName();
                String loanAmount = Double.toString(loan.getAmount());
                String monthlyInstallment = Double.toString(loan.getPeriodical());
                String toBePaid = Double.toString(loan.getToBePaid());
                
                txtAccontId.setText(AID);
                txtName.setText(Name);
                txtLoanType.setText(loanType);
                txtLoanAmount.setText(loanAmount);
                txtMonthlyInstalment.setText(monthlyInstallment);
                txtAmountToBePaid.setText(toBePaid);
            }else{
                JOptionPane.showMessageDialog(this,"Loan ID is Incorrect..");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SettlePayment1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SettlePayment1.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(txtLoanAmount.getText().trim().length()>0){
            jButton2.setEnabled(true);
        }
    }//GEN-LAST:event_txtLoanIdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SettlePayment2 st2=new SettlePayment2();
        DefaultTableModel dtm = (DefaultTableModel) st2.jt2.getModel();
        st2.LID=txtLoanId.getText();
        
        try {
            ArrayList<PaymentModel> pm=PaymentController.viewPayment(LID);
            dtm.setRowCount(0);
            for(PaymentModel p:pm){
                Object[] row={p.getPID(),p.getDate(),p.getAmount(),p.getCashOrCheque()};
                dtm.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(SettlePayment2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SettlePayment2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        mainPanel.removeAll();
        mainPanel.add(st2);
        st2.setVisible(true);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchComboActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
       
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        
        String which = txtSearch.getText();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        if (searchCombo.getSelectedItem().equals("Account ID")) {
            
            try {
                ArrayList<LoanModel> lnList = LoanController.searchLoanArray(which);
                dtm.setRowCount(0);
                if(lnList != null){
                    for (LoanModel ln : lnList) {
                        String lnType=ln.getLoanType();
                        LoanTypeModel lnT=LoanTypeController.searchLoanType(lnType);
                        AccountModel actm=AccountController.searchAccount(which);
                        CustomerModel cst=CustomerController.searchCustomer(actm.getCID());
                        Object[] row = {ln.getLID(),ln.getAID(),cst.getfName()+" "+cst.getlName(),lnT.getName(),ln.getAmount(),ln.getPeriodical(),ln.getToBePaid()};
                        dtm.addRow(row);
                    }
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ExistingCustomer.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ExistingCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
           try {
                ArrayList<LoanModel> lnList = LoanController.searchLoanArrayCustomer(which);
                dtm.setRowCount(0);
                if(lnList != null){
                    for (LoanModel ln : lnList) {
                        String lnType=ln.getLoanType();
                        AccountModel actm=AccountController.searchAccount(ln.getAID());
                        CustomerModel cst=CustomerController.searchCustomer(actm.getCID());
                        LoanTypeModel lnT=LoanTypeController.searchLoanType(lnType);
                        String customerName=cst.getfName()+" "+cst.getlName();
                        Object[] row = {ln.getLID(),ln.getAID(),customerName,lnT.getName(),ln.getAmount(),ln.getPeriodical(),ln.getToBePaid()};
                        dtm.addRow(row);
                    }
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ExistingCustomer.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ExistingCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       jButton2.setEnabled(true);
       int sel=jTable1.getSelectedRow();
       String LID=(String) jTable1.getValueAt(sel,0);
       String AID=(String) jTable1.getValueAt(sel,1);
       String name=(String) jTable1.getValueAt(sel,2);
       String loanType=(String) jTable1.getValueAt(sel,3);
       double amount=(double) jTable1.getValueAt(sel,4);
       double monthlyInstallment=(double) jTable1.getValueAt(sel,5);
       double tobePaid=(double) jTable1.getValueAt(sel,6);
       
       txtLoanId.setText(LID);
       txtAccontId.setText(AID);
       txtName.setText(name);
       txtLoanType.setText(loanType);
       txtLoanAmount.setText(Double.toString(amount));
       txtMonthlyInstalment.setText(Double.toString(monthlyInstallment));
       txtAmountToBePaid.setText(Double.toString(tobePaid));
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtLoanIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoanIdKeyReleased
        if(txtLoanId.getText().trim().length()>0){
            jButton2.setEnabled(true);
        }else{
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_txtLoanIdKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datelbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> searchCombo;
    private javax.swing.JLabel timelbl;
    private javax.swing.JTextField txtAccontId;
    private javax.swing.JTextField txtAmountToBePaid;
    private javax.swing.JTextField txtLoanAmount;
    private javax.swing.JTextField txtLoanId;
    private javax.swing.JTextField txtLoanType;
    private javax.swing.JTextField txtMonthlyInstalment;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
