/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankManagementSystem.View;

import BankManagementSystem.Controller.CustomerController;
import BankManagementSystem.Model.CustomerModel;
import static BankManagementSystem.View.MainForm.mainPanel;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static mondrian.olap.fun.vba.Vba.date;

/**
 *
 * @author NEOx
 */
public class UpdateCustomer extends javax.swing.JInternalFrame {

    /**
     * Creates new form UpdateCustomer
     */
    public UpdateCustomer() {
        initComponents();
        autoDate();
        autoTime();
        jPanel4.setVisible(false);
    }
    
    
     private void autoTime(){
    new Thread (new Runnable() {
        public void run (){
            while(true){
                Date time = new Date();
                String curDate=new SimpleDateFormat("hh:mm:ss aa").format(time);
                timelbl.setText(curDate);
                try{
                    Thread.sleep(1000);
                }catch(InterruptedException ex){
                    
                }
            }
        }
    }).start();

}

     private void autoDate(){
        Date date=new Date();
        SimpleDateFormat curDate=new SimpleDateFormat("yyyy-MM-dd");
        String newDate=curDate.format(date);
        datelbl.setText(newDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        occtxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addresstxt = new javax.swing.JTextArea();
        datelbl = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        NICtxt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        timelbl = new javax.swing.JLabel();
        DOBtxt = new com.toedter.calendar.JDateChooser();
        mbotxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        fNametxt = new javax.swing.JTextField();
        CIDtxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lNametxt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        agetxt = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(null);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jPasswordField1);
        jPasswordField1.setBounds(80, 70, 240, 30);

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(240, 110, 80, 40);

        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(190, 110, 50, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/Capture.PNG"))); // NOI18N
        jPanel4.add(jLabel11);
        jLabel11.setBounds(4, 0, 326, 160);

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 330, 160));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/changeBt.jpg"))); // NOI18N
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 890, 200, 80));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Occupation");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 510, 210, 50));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText(":");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 510, 20, 50));

        occtxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        occtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occtxtActionPerformed(evt);
            }
        });
        occtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                occtxtKeyReleased(evt);
            }
        });
        jPanel3.add(occtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 520, 430, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(":");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 20, 50));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("NIC");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 210, 50));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Date of Birth");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 210, 50));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText(":");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 20, 50));

        addresstxt.setColumns(20);
        addresstxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addresstxt.setRows(5);
        jScrollPane2.setViewportView(addresstxt);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 310, 430, -1));

        datelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        datelbl.setForeground(new java.awt.Color(255, 255, 255));
        datelbl.setText("16");
        jPanel3.add(datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, 320, -1));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-vertical-line.png"))); // NOI18N
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 20, 30, 90));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Years");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, 100, 50));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(":");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 20, 50));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText(":");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 310, 20, 50));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(":");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 20, 50));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText(":");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 20, 50));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText(":");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 580, 20, 50));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(":");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 20, 50));

        NICtxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NICtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NICtxtActionPerformed(evt);
            }
        });
        NICtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NICtxtKeyReleased(evt);
            }
        });
        jPanel3.add(NICtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 430, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/backButton.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 910, 150, 50));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Address");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 300, 210, 70));

        timelbl.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        timelbl.setForeground(new java.awt.Color(255, 255, 255));
        timelbl.setText("08:16:00");
        jPanel3.add(timelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 20, 360, 90));

        DOBtxt.setDateFormatString("yyyy MM dd");
        DOBtxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        DOBtxt.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                DOBtxtComponentAdded(evt);
            }
        });
        DOBtxt.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                DOBtxtAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(DOBtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 430, 40));

        mbotxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mbotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mbotxtKeyReleased(evt);
            }
        });
        jPanel3.add(mbotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 590, 430, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Mobile no.");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 580, 210, 50));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Gender");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 700, 210, 50));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText(":");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 700, 20, 50));

        female.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.setOpaque(false);
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel3.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 710, 140, 30));

        male.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        male.setOpaque(false);
        jPanel3.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 710, 130, 30));

        fNametxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNametxtActionPerformed(evt);
            }
        });
        fNametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fNametxtKeyReleased(evt);
            }
        });
        jPanel3.add(fNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 430, -1));

        CIDtxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIDtxtActionPerformed(evt);
            }
        });
        jPanel3.add(CIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 430, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("First Name");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 210, 70));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Last Name");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 210, 70));

        lNametxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNametxtActionPerformed(evt);
            }
        });
        lNametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lNametxtKeyReleased(evt);
            }
        });
        jPanel3.add(lNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 430, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Age");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 620, 130, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-horizontal-line.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 780, 40));

        agetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(agetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 130, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer ID");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 210, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Change Customer Details");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 880, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/gold-horizontal-line.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1910, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1060));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1060));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1060));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1920, 1060));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1060));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/black Transparent.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1060));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankManagementSystem/View/istock000003037994medium.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 1100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String CID;
    String fName;
    String lName;
    String DOB;
    String age;
    String gender;
    String address;
    String NIC;
    String occ;
    String mbo;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            CID = CIDtxt.getText();
       
            fName = fNametxt.getText();
            lName = lNametxt.getText();
            DOB = DateFormat.getInstance().format(DOBtxt.getDate());
            age =Integer.toString((int) agetxt.getValue());
            gender=null;
            if(male.isSelected()){
                gender="male";
            }else{
                gender="female";
            }
            address = addresstxt.getText();
            NIC = NICtxt.getText();
            occ = occtxt.getText();
            mbo = mbotxt.getText();
               
           jPanel4.setVisible(true);
           jPasswordField1.requestFocus();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void occtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occtxtActionPerformed
        mbotxt.requestFocus();
    }//GEN-LAST:event_occtxtActionPerformed

    private void NICtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NICtxtActionPerformed
        if(NICtxt.getText() != null){
            String NIC=NICtxt.getText();
            String syy=NIC.substring(0,2);
            String smm=NIC.substring(2,5);
            int yy=Integer.parseInt(19+syy);
            int mm=Integer.parseInt(smm);

            if(mm>=500){
                female.setSelected(true);
                mm-=500;
            }else{
                male.setSelected(true);
            }

            if(yy % 4 != 0){
                mm=mm-1;
            }

            Calendar c1=Calendar.getInstance();
            c1.set(Calendar.YEAR, yy);
            c1.set(Calendar.DAY_OF_YEAR, mm);
            Date d1=c1.getTime();
            DOBtxt.setDate(d1);

            Date date=new Date();
            SimpleDateFormat curDate=new SimpleDateFormat("yyyy");
            String newDate=curDate.format(date);
            int year=Integer.parseInt(newDate);

            int age = year-yy;
            agetxt.setValue(age);
            addresstxt.requestFocus();
        }else{
            NICtxt.setText("None");
        }
    }//GEN-LAST:event_NICtxtActionPerformed

    private void DOBtxtComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_DOBtxtComponentAdded

    }//GEN-LAST:event_DOBtxtComponentAdded

    private void DOBtxtAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_DOBtxtAncestorAdded

    }//GEN-LAST:event_DOBtxtAncestorAdded

    private void mbotxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mbotxtKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.phoneNumber(mbotxt, evt);
        }

        if(fNametxt.getText().length()>0){
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_mbotxtKeyReleased

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void fNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNametxtActionPerformed
        lNametxt.requestFocus();
    }//GEN-LAST:event_fNametxtActionPerformed

    private void CIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIDtxtActionPerformed
        String CID = CIDtxt.getText();
        try {
            CustomerModel cst=CustomerController.searchCustomer(CID);
            if(cst != null){
                int age = Integer.parseInt(cst.getAge());
                fNametxt.setText(cst.getfName());
                lNametxt.setText(cst.getlName());
                agetxt.setValue(age);
                NICtxt.setText(cst.getNIC());
                occtxt.setText(cst.getOccupation());
                addresstxt.setText(cst.getAddress());
                mbotxt.setText(cst.getMobileNo());
                String gender=cst.getGender();
                
                
                if(gender=="male"){
                    male.setSelected(true);
                }else{
                    female.setSelected(true);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Customer ID is incorrect....");
                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoanFindCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LoanFindCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_CIDtxtActionPerformed

    private void lNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNametxtActionPerformed
        NICtxt.requestFocus();
    }//GEN-LAST:event_lNametxtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ManageCustomerMenu m1 = new ManageCustomerMenu();
        mainPanel.removeAll();
        mainPanel.add(m1);
        m1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jPanel4.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
            jPanel4.setVisible(false);
            CustomerModel cst=new CustomerModel(CID,fName,lName,DOB,age,gender,address,occ,NIC,mbo);
               
                    try {
                        boolean res=CustomerController.updateCustomer(cst);
                        if(res){
                            JOptionPane.showMessageDialog(this,"Updated Successfully..!!");
                            Homepage h1 = new Homepage();
                            mainPanel.removeAll();
                            mainPanel.add(h1);
                            h1.setVisible(true);
                        }else{
                            JOptionPane.showMessageDialog(this,"Update Failed..!!");
                        }
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
                    }        
        
            jPanel4.setVisible(false);
            jPanel4.setVisible(true);
            jPasswordField1.requestFocus();
        
        
         
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        jButton5.doClick();
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void fNametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNametxtKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.name(fNametxt);
        }
    }//GEN-LAST:event_fNametxtKeyReleased

    private void lNametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNametxtKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.name(lNametxt);
        }
    }//GEN-LAST:event_lNametxtKeyReleased

    private void NICtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NICtxtKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.validateNIC(NICtxt);
        }
    }//GEN-LAST:event_NICtxtKeyReleased

    private void occtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_occtxtKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            Validation.Validation.name(occtxt);
        }
    }//GEN-LAST:event_occtxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CIDtxt;
    private com.toedter.calendar.JDateChooser DOBtxt;
    private javax.swing.JTextField NICtxt;
    private javax.swing.JTextArea addresstxt;
    private javax.swing.JSpinner agetxt;
    private javax.swing.JLabel datelbl;
    private javax.swing.JTextField fNametxt;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lNametxt;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mbotxt;
    private javax.swing.JTextField occtxt;
    private javax.swing.JLabel timelbl;
    // End of variables declaration//GEN-END:variables
}
